### PR TITLE
dress up

### PR DESCRIPTION
**Pull request by varun-Tad**
Created home page. Please review

### CODE REVIEW

**Review by rahulk31 — APPROVED** [review]
Code looks good to me.
But I would suggest to rethink on how you are planning to put the content together overall. You can have categories section from where you can redirect user to those relevant pages. Then some offers section. Something like deal of the day. You can take inspiration from amazon and flipkart. 
As of now. It is fine, good to merge. 👍

**Comment by varun-Tad** [comment]
Thanks @rahulk31.Yes agreed. I'll maybe add a categories section as you suggested.

**Review by prankurpandeyy — APPROVED** [review]

**Comment by prankurpandeyy** [comment]
over all the code looks good to me .

**Comment by iamalhera** [comment]
code looks fine,  make little more difference of color/background-color on hovering of buttons, go ahead to merge

**Comment by varun-Tad** [comment]
Made the suggested changes.Thanks for the review.  @iprankurpandey @iamalhera

**Pull request merged**
